server.port=8085

spring.application.name=api-gateway

# Route to AuthService running on port 8080
spring.cloud.gateway.routes[0].id=auth-service-route
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/health, /users/**, /auth/**, /api/auth/**, /api/user/**


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/